"""Modelo inicial da reestruturação (Fase 1).

Cria as tabelas descritas em docs/MODELO_DE_DADOS.md: pessoa, tipo_amostra,
classe, coleta, imagem, job_segmentacao, regiao e anotacao.

Revision ID: 749f4190263e
Revises: 
Create Date: 2026-09-25 16:40:46.232076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749f4190263e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('nome_normalizado', sa.String(length=120), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criada_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pessoa')),
    sa.UniqueConstraint('nome_normalizado', name=op.f('uq_pessoa_nome_normalizado'))
    )
    op.create_table('tipo_amostra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tipo_amostra')),
    sa.UniqueConstraint('codigo', name=op.f('uq_tipo_amostra_codigo'))
    )
    op.create_table('classe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_amostra_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('cor', sa.String(length=7), nullable=False),
    sa.Column('tecla_atalho', sa.String(length=1), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_amostra_id'], ['tipo_amostra.id'], name=op.f('fk_classe_tipo_amostra_id_tipo_amostra')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classe')),
    sa.UniqueConstraint('tipo_amostra_id', 'codigo', name=op.f('uq_classe_tipo_amostra_id_codigo')),
    sa.UniqueConstraint('tipo_amostra_id', 'tecla_atalho', name=op.f('uq_classe_tipo_amostra_id_tecla_atalho'))
    )
    op.create_table('coleta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_amostra_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('fazenda', sa.String(length=120), nullable=True),
    sa.Column('talhao', sa.String(length=80), nullable=True),
    sa.Column('variedade', sa.String(length=80), nullable=True),
    sa.Column('data_coleta', sa.Date(), nullable=True),
    sa.Column('coletor_id', sa.Integer(), nullable=True),
    sa.Column('criada_em', sa.DateTime(), nullable=False),
    sa.Column('atualizada_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coletor_id'], ['pessoa.id'], name=op.f('fk_coleta_coletor_id_pessoa')),
    sa.ForeignKeyConstraint(['tipo_amostra_id'], ['tipo_amostra.id'], name=op.f('fk_coleta_tipo_amostra_id_tipo_amostra')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coleta'))
    )
    op.create_table('imagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coleta_id', sa.Integer(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('extensao', sa.String(length=5), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('largura', sa.Integer(), nullable=False),
    sa.Column('altura', sa.Integer(), nullable=False),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=False),
    sa.Column('capturada_em', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('origem', sa.Enum('camera', 'arquivo', 'importacao', name='origemimagem', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('aguardando', 'segmentando', 'pronta', 'erro', name='statusimagem', native_enum=False, length=20), nullable=False),
    sa.Column('ja_segmentada', sa.Boolean(), nullable=False),
    sa.Column('enviada_por_id', sa.Integer(), nullable=True),
    sa.Column('enviada_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint('largura > 0 AND altura > 0', name=op.f('ck_imagem_dimensoes_positivas')),
    sa.ForeignKeyConstraint(['coleta_id'], ['coleta.id'], name=op.f('fk_imagem_coleta_id_coleta'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enviada_por_id'], ['pessoa.id'], name=op.f('fk_imagem_enviada_por_id_pessoa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_imagem')),
    sa.UniqueConstraint('coleta_id', 'hash_sha256', name=op.f('uq_imagem_coleta_id_hash_sha256'))
    )
    with op.batch_alter_table('imagem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imagem_coleta_id'), ['coleta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_imagem_hash_sha256'), ['hash_sha256'], unique=False)

    op.create_table('job_segmentacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagem_id', sa.Integer(), nullable=False),
    sa.Column('motor', sa.String(length=40), nullable=False),
    sa.Column('versao_motor', sa.String(length=40), nullable=True),
    sa.Column('parametros', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('na_fila', 'processando', 'concluido', 'erro', name='statusjob', native_enum=False, length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(), nullable=True),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.Column('num_regioes', sa.Integer(), nullable=True),
    sa.Column('mensagem_erro', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['imagem_id'], ['imagem.id'], name=op.f('fk_job_segmentacao_imagem_id_imagem'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_segmentacao'))
    )
    with op.batch_alter_table('job_segmentacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_segmentacao_imagem_id'), ['imagem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_segmentacao_status'), ['status'], unique=False)

    op.create_table('regiao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagem_id', sa.Integer(), nullable=False),
    sa.Column('poligono', sa.JSON(), nullable=False),
    sa.Column('bbox_x', sa.Integer(), nullable=False),
    sa.Column('bbox_y', sa.Integer(), nullable=False),
    sa.Column('bbox_largura', sa.Integer(), nullable=False),
    sa.Column('bbox_altura', sa.Integer(), nullable=False),
    sa.Column('area_px', sa.Integer(), nullable=False),
    sa.Column('origem', sa.Enum('automatica', 'manual', 'importada', name='origemregiao', native_enum=False, length=20), nullable=False),
    sa.Column('motor', sa.String(length=40), nullable=True),
    sa.Column('versao_motor', sa.String(length=40), nullable=True),
    sa.Column('pontuacao', sa.Double(), nullable=True),
    sa.Column('criada_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint('area_px > 0', name=op.f('ck_regiao_area_positiva')),
    sa.CheckConstraint('pontuacao IS NULL OR (pontuacao >= 0 AND pontuacao <= 1)', name=op.f('ck_regiao_pontuacao_entre_0_e_1')),
    sa.ForeignKeyConstraint(['imagem_id'], ['imagem.id'], name=op.f('fk_regiao_imagem_id_imagem'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regiao'))
    )
    with op.batch_alter_table('regiao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regiao_imagem_id'), ['imagem_id'], unique=False)

    op.create_table('anotacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regiao_id', sa.Integer(), nullable=False),
    sa.Column('classe_id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.Column('origem', sa.Enum('manual', 'importada', 'modelo', name='origemanotacao', native_enum=False, length=20), nullable=False),
    sa.Column('confianca', sa.Double(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criada_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint('confianca IS NULL OR (confianca >= 0 AND confianca <= 1)', name=op.f('ck_anotacao_confianca_entre_0_e_1')),
    sa.ForeignKeyConstraint(['classe_id'], ['classe.id'], name=op.f('fk_anotacao_classe_id_classe'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], name=op.f('fk_anotacao_pessoa_id_pessoa')),
    sa.ForeignKeyConstraint(['regiao_id'], ['regiao.id'], name=op.f('fk_anotacao_regiao_id_regiao'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anotacao'))
    )
    with op.batch_alter_table('anotacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anotacao_classe_id'), ['classe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anotacao_pessoa_id'), ['pessoa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anotacao_regiao_id'), ['regiao_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anotacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anotacao_regiao_id'))
        batch_op.drop_index(batch_op.f('ix_anotacao_pessoa_id'))
        batch_op.drop_index(batch_op.f('ix_anotacao_classe_id'))

    op.drop_table('anotacao')
    with op.batch_alter_table('regiao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regiao_imagem_id'))

    op.drop_table('regiao')
    with op.batch_alter_table('job_segmentacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_segmentacao_status'))
        batch_op.drop_index(batch_op.f('ix_job_segmentacao_imagem_id'))

    op.drop_table('job_segmentacao')
    with op.batch_alter_table('imagem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imagem_hash_sha256'))
        batch_op.drop_index(batch_op.f('ix_imagem_coleta_id'))

    op.drop_table('imagem')
    op.drop_table('coleta')
    op.drop_table('classe')
    op.drop_table('tipo_amostra')
    op.drop_table('pessoa')
    # ### end Alembic commands ###
