"""Motor de segmentação por tipo de amostra (Fase 2).

Adiciona tipo_amostra.motor_padrao, preenchido a partir do campo `motor` dos
arquivos taxonomias/*.yaml na sincronização ao iniciar.

Revision ID: 8b71c2082e0f
Revises: 749f4190263e
Create Date: 2026-09-25 17:31:59.442709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b71c2082e0f'
down_revision = '749f4190263e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_amostra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motor_padrao', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_amostra', schema=None) as batch_op:
        batch_op.drop_column('motor_padrao')

    # ### end Alembic commands ###
